### ISSUE TITLE
Clock Puzzle

### ISSUE THREAD

**Issue by DevStewart19** [HuskyGameDev/2020f-team10#132]
- [x] Art
- [x] Clock hands going to safe combo
- [x] Enter Safe Combo
- [x] Recieve blinders from Safe

**Comment by rossquentin** [comment]
@DevStewart19 
Need feedback on 293e15a5127a14cbaaf8eb4968c153446d727372 with regards to changed ink dialogs

**Comment by rossquentin** [comment]
Need artwork for blinders.
